[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 57600
board_build.filesystem = littlefs
lib_deps =
  bblanchon/ArduinoJson@^7.0.0
  h2zero/NimBLE-Arduino@^1.4.2
  marian-craciunescu/ESP32Ping@^1.7
